const test = require("node:test");
const assert = require("node:assert/strict");
const { Sheet } = require("../src/sheet");
test("case 0 =1+1", () => { const sh = new Sheet(); sh.set("A1", "=1+1"); assert.deepEqual(sh.get("A1"), 2); });
test("case 1 =2^3^2", () => { const sh = new Sheet(); sh.set("A1", "=2^3^2"); assert.deepEqual(sh.get("A1"), 512); });
test("case 2 =-2^2", () => { const sh = new Sheet(); sh.set("A1", "=-2^2"); assert.deepEqual(sh.get("A1"), 4); });
test("case 3 =50%", () => { const sh = new Sheet(); sh.set("A1", "=50%"); assert.deepEqual(sh.get("A1"), 0.5); });
test("case 4 =SUM(1,2)", () => { const sh = new Sheet(); sh.set("A1", "=SUM(1,2)"); assert.deepEqual(sh.get("A1"), 3); });
test("case 5 =ROUND(2.5,0)", () => { const sh = new Sheet(); sh.set("A1", "=ROUND(2.5,0)"); assert.deepEqual(sh.get("A1"), 3); });
test("case 6 =MOD(-7,3)", () => { const sh = new Sheet(); sh.set("A1", "=MOD(-7,3)"); assert.deepEqual(sh.get("A1"), 2); });
test("case 7 =IF(1,2,3)", () => { const sh = new Sheet(); sh.set("A1", "=IF(1,2,3)"); assert.deepEqual(sh.get("A1"), 2); });
test("case 8 =LEN(\"ab\")", () => { const sh = new Sheet(); sh.set("A1", "=LEN(\"ab\")"); assert.deepEqual(sh.get("A1"), 2); });
test("case 9 =UPPER(\"a\")", () => { const sh = new Sheet(); sh.set("A1", "=UPPER(\"a\")"); assert.deepEqual(sh.get("A1"), "A"); });
test("case 10 =TRIM(\" a  b \")", () => { const sh = new Sheet(); sh.set("A1", "=TRIM(\" a  b \")"); assert.deepEqual(sh.get("A1"), "a b"); });
test("case 11 =LEFT(\"abc\",2)", () => { const sh = new Sheet(); sh.set("A1", "=LEFT(\"abc\",2)"); assert.deepEqual(sh.get("A1"), "ab"); });
test("case 12 =FIND(\"b\",\"abc\")", () => { const sh = new Sheet(); sh.set("A1", "=FIND(\"b\",\"abc\")"); assert.deepEqual(sh.get("A1"), 2); });
test("case 13 =REPT(\"x\",3)", () => { const sh = new Sheet(); sh.set("A1", "=REPT(\"x\",3)"); assert.deepEqual(sh.get("A1"), "xxx"); });
test("case 14 =CHOOSE(1,\"a\")", () => { const sh = new Sheet(); sh.set("A1", "=CHOOSE(1,\"a\")"); assert.deepEqual(sh.get("A1"), "a"); });
test("case 15 =1/0", () => { const sh = new Sheet(); sh.set("A1", "=1/0"); assert.deepEqual(sh.get("A1"), "#DIV/0!"); });
test("case 16 =FOO()", () => { const sh = new Sheet(); sh.set("A1", "=FOO()"); assert.deepEqual(sh.get("A1"), "#NAME?"); });
test("case 17 =1+", () => { const sh = new Sheet(); sh.set("A1", "=1+"); assert.deepEqual(sh.get("A1"), "#ERROR!"); });
test("case 18 =AND(1,1)", () => { const sh = new Sheet(); sh.set("A1", "=AND(1,1)"); assert.deepEqual(sh.get("A1"), true); });
test("case 19 =NOT(1)", () => { const sh = new Sheet(); sh.set("A1", "=NOT(1)"); assert.deepEqual(sh.get("A1"), false); });
test("case 20 =ISNUMBER(1)", () => { const sh = new Sheet(); sh.set("A1", "=ISNUMBER(1)"); assert.deepEqual(sh.get("A1"), true); });
